# Pyconnect Server configuration file. 

[app]
environment = "development"
debug = true

[server]
host = "127.0.0.1"
port = 1234
threading = true
max_threads = 1

[logs]
logfile = "logs/logs.log"
